### PR TITLE
Bump github.com/containerd/containerd to 1.5.9

### PR DESCRIPTION
**Pull request by julian-hj**
## Is there a related GitHub Issue?

No

## What is this change about?

To clear security warnings from dependabot in our github repo.

It doesn't seem like there is an actual vulnerability afoot, since we don't spawn containers from our executables, but the warning is annoying, and it's dangerous to get used to ignoring warnings.

## Does this PR introduce a breaking change?

no
## Acceptance Steps

none

## Tag your pair, your PM, and/or team

@davewalter @tcdowney

### CODE REVIEW

**Review by tcdowney — APPROVED** [review]
LGTM 😌

**Review by davewalter — COMMENTED** [review]
Does this actually resolve the warning? There are still vulnerable versions of `containerd` (versions between `1.5.0` and `1.5.8`) in the `go.sum` file.

Do we know which of the direct dependencies introduced the various versions? I suspect we need to upgrade them to fully eliminate the references.

**Comment by tcdowney** [comment]
Looking at `go mod graph`... quite a bit of buildpack/registry related dependencies include it.

```
$ go mod graph | grep " github.com/containerd/containerd@v1.5"
code.cloudfoundry.org/cf-k8s-controllers github.com/containerd/containerd@v1.5.9
github.com/buildpacks/imgutil@v0.0.0-20211203200417-76206845baac github.com/containerd/containerd@v1.5.8
github.com/buildpacks/pack@v0.23.0 github.com/containerd/containerd@v1.5.8
github.com/google/go-containerregistry@v0.8.0 github.com/containerd/containerd@v1.5.8
github.com/pivotal/kpack@v0.5.0 github.com/containerd/containerd@v1.5.4
github.com/google/go-containerregistry@v0.7.0 github.com/containerd/containerd@v1.5.7
github.com/containerd/aufs@v1.0.0 github.com/containerd/containerd@v1.5.0-beta.3
github.com/containerd/imgcrypt@v1.1.1 github.com/containerd/containerd@v1.5.0-rc.0
github.com/containerd/nri@v0.1.0 github.com/containerd/containerd@v1.5.0-beta.3
github.com/containerd/zfs@v1.0.0 github.com/containerd/containerd@v1.5.0-beta.3
github.com/google/go-containerregistry@v0.5.2-0.20210609162550-f0ce2270b3b4 github.com/containerd/containerd@v1.5.2
github.com/google/go-containerregistry@v0.6.0 github.com/containerd/containerd@v1.5.2
github.com/Microsoft/hcsshim@v0.8.16 github.com/containerd/containerd@v1.5.0-beta.4
github.com/google/go-containerregistry@v0.5.2-0.20210604130445-3bfab55f3bd9 github.com/containerd/containerd@v1.5.2
github.com/Microsoft/hcsshim@v0.8.18 github.com/containerd/containerd@v1.5.1
github.com/Microsoft/hcsshim@v0.8.21 github.com/containerd/containerd@v1.5.1
github.com/Microsoft/hcsshim@v0.8.15 github.com/containerd/containerd@v1.5.0-beta.1
github.com/Microsoft/hcsshim/test@v0.0.0-20210227013316-43a75bb4edd3 github.com/containerd/containerd@v1.5.0-beta.1
```

**Comment by julian-hj** [comment]
> Does this actually resolve the warning? There are still vulnerable versions of `containerd` (versions between `1.5.0` and `1.5.8`) in the `go.sum` file.

Yeah, it does seem to have got rid of the ugly banner. Since we don't think the vulnerability was real for anything other than envtest, I guess...job done?🤷

**Pull request merged**
