### PR TITLE
Add authentication middleware

### PR DESCRIPTION
**Pull request by gcapizzi**
This adds a middleware that will block any request coming from users with missing or invalid authentication credentials.

### CODE REVIEW

**Comment by tcdowney** [comment]
Nice!
```
09:51 $ cf curl /v3/processes/51f740bd-494d-11ec-8560-ce6c6a3b098d/stats

{"resources":[{"type":"web","index":0,"state":"RUNNING","host":null,"instance_ports":[],"uptime":null,"mem_quota":null,"disk_quota":null,"fds_quota":null,"isolation_segment":null,"details":null}]}

09:51 $ curl localhost:9000/v3/processes/51f740bd-494d-11ec-8560-ce6c6a3b098d/stats

{"errors":[{"detail":"Authentication error","title":"CF-NotAuthenticated","code":10002}]}
```

**Comment by tcdowney** [comment]
@gcapizzi If you're using `curl` instead of the `cf` CLI what would be the best way to manually set up the `Authorization` header?

On CF for VMs I would use `curl -H "Authorization: $(cf oauth-token)" ...`.

**Comment by gcapizzi** [comment]
> @gcapizzi If you're using `curl` instead of the `cf` CLI what would be the best way to manually set up the `Authorization` header?
> 
> On CF for VMs I would use `curl -H "Authorization: $(cf oauth-token)" ...`.

We don't have a good way at the moment 😕  We could implement `cf oauth-token` though! I'll add a story and we can see when to prioritise it.

**Review by danail-branekov — COMMENTED** [review]
lgtm

**Review by danail-branekov — APPROVED** [review]

**Pull request merged**
